# Name of your application. Used to uniquely configure containers.
service: sm_simulator

# Name of the container image.
image: niciliketo/sm-simulator

# Deploy to these servers.
servers:
  web:
    - 65.21.155.125

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
proxy:
  ssl: true
  host: sm.iliketo.net

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: ghcr.io
  username: niciliketo
  # Always use an access token rather than real password when possible.
  password:
    - GITHUB_TOKEN

# Configure the image builder.
builder:
  arch: amd64

# Aliases are triggered with "kamal <alias>". You can overwrite arguments on invocation:
# "kamal logs" will tail logs from the web server.
aliases:
  shell: app exec --interactive --reuse "sh"
  logs: app logs -f
